# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
  routing_loader:
    default_format: json
    include_format: false
  body_listener: true
  format_listener:
    rules:
      - { path: ^/, priorities: [ html, json, xml ], fallback_format: ~, prefer_extension: true }
      - { path: '^/', priorities: [ 'html', '*/*'], fallback_format: ~, prefer_extension: true }
  param_fetcher_listener: true
  access_denied_listener:
    json: true
  view:
    view_response_listener: true
    formats:
      json: true