fos_user:
  db_driver: orm
  firewall_name: main
  user_class: App\Entity\User
  from_email:
    address: victor@taskmanager.com
    sender_name: Victor Ndu
  registration:
    #        form:
    #            type: AppBundle\Form\UserRegisterType
    confirmation:
      enabled: true
      template:   FOSUserBundle:Registration:email.txt.twig
      from_email:
        address:        "no-reply@joeymasip.com"
        sender_name:    "No Reply Registration"
  resetting:
    email:
      template:   FOSUserBundle:Resetting:email.txt.twig